### ISSUE TITLE
Loosen up the requirements

### ISSUE THREAD

**Issue by DOsinga** [gw-moore/pyfredapi#8]
Not sure this is really a feature request, but the packages specified seem rather strict. Does it really not work with earlier versions of plotly? I have a setup where we have some legacy stuff installed and I can't use this very nice package because it has plotly 5.8.

**Comment by gw-moore** [comment]
@DOsinga thanks for making this issue. I've released a new version of the package which only requires >= the latest major version of each of the required dependencies.
